version: '3.9'
name: readme-notification

services:
  typoteka.notify.fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: "readme.notification.fakesmtp"
    hostname: "readme.notification.fakesmtp"
    ports:
      - "8025:8025"
      - "1085:8080"
