version: '3.9'
services:
  readme-user-mongo:
    image: mongo:4.4
    restart: always
    container_name: readme-user-mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017

    healthcheck:
      test: [ "CMD-SHELL", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

    volumes:
      - readme.mongo.user:/data/db
    networks:
      - mongo-compose-network

  readme-user-mongo-ui:
    image: mongo-express:latest
    restart: always
    container_name: readme-user-mongo-ui
    ports:
      - 9000:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: readme-user-mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    links:
      - readme-user-mongo
    networks:
      - mongo-compose-network


volumes:
  readme.mongo.user:

networks:
  mongo-compose-network:
    driver: bridge


