version: '3.9'
name: readme-upload

services:
  readme.upload.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.upload.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017

    healthcheck:
      test: [ "CMD-SHELL", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

    volumes:
      - readme.mongo.upload:/data/db

    networks:
      - update-service-network

  readme.upload.mongo.ui:
    image: mongo-express:latest
    restart: always
    container_name: readme.upload.mongo.ui
    ports:
      - ${MONGO_UI_PORT}:8081

    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}

    networks:
      - update-service-network

volumes:
  readme.mongo.upload:

networks:
  update-service-network:
    driver: bridge
